package qcm;

import java.awt.Font;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import qcm.mysql.Person;
import qcm.mysql.UserDaoImpl;

public class loginForm extends javax.swing.JFrame {

    public loginForm() {
        initComponents();
 
                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblNewAccount = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        lblErr1 = new javax.swing.JLabel();
        lblErr2 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnConnecter = new javax.swing.JButton();
        btnRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini projet java: Se connecter");
        setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qcm/img/padlock-10-256.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, 300));

        lblNewAccount.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNewAccount.setForeground(new java.awt.Color(36, 47, 65));
        lblNewAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qcm/img/add-user.png"))); // NOI18N
        lblNewAccount.setText("Besoin d'un compte ! créer un nouveau");
        lblNewAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNewAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNewAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNewAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNewAccountMouseExited(evt);
            }
        });
        jPanel1.add(lblNewAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 490));

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Se connecter");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, 50));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("VOTRE NOM UTILISATEUR");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 50));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("MOT DE PASSE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 340, 20));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 340, 20));

        lblErr1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblErr1.setForeground(new java.awt.Color(255, 0, 0));
        lblErr1.setText("* Veuillez renseigner ce champ");
        lblErr1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(lblErr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 330, 20));
        lblErr1.setVisible(false);

        lblErr2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblErr2.setForeground(new java.awt.Color(255, 0, 0));
        lblErr2.setText("* Veuillez renseigner ce champ");
        lblErr2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(lblErr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 330, 20));
        lblErr2.setVisible(false);
        jPanel2.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 330, 40));
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 330, 40));

        btnConnecter.setBackground(new java.awt.Color(51, 153, 255));
        btnConnecter.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnConnecter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qcm/img/login (2).png"))); // NOI18N
        btnConnecter.setText("  Se connecter");
        btnConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnecterActionPerformed(evt);
            }
        });
        jPanel2.add(btnConnecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 160, 50));

        btnRetour.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnRetour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qcm/img/left-arrow.png"))); // NOI18N
        btnRetour.setText("  Retour");
        btnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourActionPerformed(evt);
            }
        });
        jPanel2.add(btnRetour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 160, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 360, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblNewAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewAccountMouseClicked
        this.setVisible(false);
        new newAccoutnForm().setVisible(true);
    }//GEN-LAST:event_lblNewAccountMouseClicked

    private void btnConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnecterActionPerformed
        String username = txtUserName.getText().toLowerCase().trim();
        String password = txtPassword.getText();
        String md5pass = appUtils.md5Hash(password);

        boolean formChecked = false;
        String fieldError1 = null, fieldError2 = null;  //contient les erreurs de label

        if (username.equals("")) {
            formChecked = false;
            fieldError1 = "* ce champ ne peut etre vide";

        } else if (username.length() < 4) {
            formChecked = false;
            fieldError1 = ("* au minimaum 4 caractères");
        } else {
            lblErr1.setVisible(false);
            fieldError1 = null;
        }

        if (fieldError1 != null) {
            lblErr1.setText(fieldError1);
            lblErr1.setVisible(true);
            txtUserName.requestFocus();
        }

        if (password.equals("")) {
            formChecked = false;
            fieldError2 = "* ce champ ne peut etre vide";

        } else if (password.length() < 4) {
            formChecked = false;
            fieldError2 = ("* au minimaum 4 caractères");
        } else {
            lblErr2.setVisible(false);
            fieldError2 = null;
        }

        if (fieldError2 != null) {
            lblErr2.setText(fieldError2);
            lblErr2.setVisible(true);
            txtPassword.requestFocus();
        }

        formChecked = (fieldError2 == null && fieldError1 == null);

        //si tout ok 
        if (formChecked) {
            UserDaoImpl pdi = new UserDaoImpl();
            Person user = new Person();

            md5pass = appUtils.md5Hash(password);
            user = pdi.fetchUser(username, md5pass);

            //si l'utilisateur n'est pas trouvé 
            if (user.getUsername() == null || user.getUserpass() == null) {
                javax.swing.JOptionPane.showMessageDialog(null, "Utilisateur introuvable", "Mini projet", ERROR_MESSAGE);
                lblErr1.setVisible(false);
                lblErr2.setVisible(false);
                //txtPassword.setText("");
                txtUserName.requestFocus();
            } else {
                //rederiction vers le form qcmForm 
                this.setVisible(false);
                appUtils.user = user;
                System.out.println(appUtils.user.toString());
                new qcmForm().setVisible(true);

            }

        }


    }//GEN-LAST:event_btnConnecterActionPerformed

    private void btnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourActionPerformed
         this.setVisible(false);
        new mainForm().setVisible(true);
    }//GEN-LAST:event_btnRetourActionPerformed

    private void lblNewAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewAccountMouseEntered
        Font f = lblNewAccount.getFont() ; 
        lblNewAccount.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
    }//GEN-LAST:event_lblNewAccountMouseEntered

    private void lblNewAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNewAccountMouseExited
        Font f = lblNewAccount.getFont() ; 
        lblNewAccount.setFont(f.deriveFont(f.getStyle() &  ~Font.BOLD));
    }//GEN-LAST:event_lblNewAccountMouseExited

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnecter;
    private javax.swing.JButton btnRetour;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblErr1;
    private javax.swing.JLabel lblErr2;
    private javax.swing.JLabel lblNewAccount;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
