package qcm;

import javax.swing.JOptionPane;

public class mainForm extends javax.swing.JFrame {

    public mainForm() {
        initComponents();
        jLabel5.setText(appUtils.Copyright);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBestScore = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        btnNewGame1 = new javax.swing.JButton();
        btnNewAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("jeuQuiz::Louhichi Amine");
        setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qcm/img/main-icon.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 280, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 490));

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Jeu Quiz");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 290, 10));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Bienvenue");
        jLabel7.setToolTipText("");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 290, 50));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("<dynamic>");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 260, 20));

        btnBestScore.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnBestScore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qcm/img/medal.png"))); // NOI18N
        btnBestScore.setText("  Meuilleur score");
        btnBestScore.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBestScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBestScoreActionPerformed(evt);
            }
        });
        jPanel2.add(btnBestScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 230, 50));

        btnAbout.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qcm/img/computer.png"))); // NOI18N
        btnAbout.setText("  A propos");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jPanel2.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 230, 50));

        btnQuit.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnQuit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qcm/img/logout.png"))); // NOI18N
        btnQuit.setText("  Quitter");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel2.add(btnQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 230, 50));

        btnNewGame1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnNewGame1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qcm/img/gamepad.png"))); // NOI18N
        btnNewGame1.setText("  Nouveau jeu");
        btnNewGame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewGame1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnNewGame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 230, 50));

        btnNewAccount.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnNewAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qcm/img/add-user.png"))); // NOI18N
        btnNewAccount.setText("Créer un compte");
        btnNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccountActionPerformed(evt);
            }
        });
        jPanel2.add(btnNewAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 230, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 310, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed

        confirmQuit();
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAccountActionPerformed
        this.setVisible(false);
        new newAccoutnForm().setVisible(true);

    }//GEN-LAST:event_btnNewAccountActionPerformed

    private void btnBestScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBestScoreActionPerformed
        this.setVisible(false);
        new bestScoreForm().setVisible(true);
    }//GEN-LAST:event_btnBestScoreActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        this.setVisible(false);
        new aboutForm().setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnNewGame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewGame1ActionPerformed
        // si l'utilisateur n'est pas s'ithentifier
        if (appUtils.user == null) {
            this.setVisible(false);
            new loginForm().setVisible(true);
        } else {
            this.setVisible(false);
            new qcmForm().setVisible(true);
        }
    }//GEN-LAST:event_btnNewGame1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        confirmQuit();


    }//GEN-LAST:event_formWindowClosing

    private void confirmQuit() {
        int reponse = JOptionPane.showConfirmDialog(null, "Voulez vous vraiment quitter", "Confirmation",
                JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (reponse == JOptionPane.YES_OPTION) {
            dispose();
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnBestScore;
    private javax.swing.JButton btnNewAccount;
    private javax.swing.JButton btnNewGame1;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
