package qcm;

import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import qcm.mysql.Person;

public class newAccoutnForm extends javax.swing.JFrame {
 String fieldError1 = null, fieldError2 = null, fieldError3 = null;  //contient les erreurs de label
    public newAccoutnForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblErr1 = new javax.swing.JLabel();
        lblErr2 = new javax.swing.JLabel();
        lblErr3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPasswordConfirm = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        btnNewAccount = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini projet java: Créer un compte");
        setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qcm/img/add-user-256.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 250, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 490));

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Creer un nouveau compte");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 260, 40));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("VOTRE NOM UTILISATEUR");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 50));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("REPETER LE MOT DE PASSE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 360, 10));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 360, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("MOT DE PASSE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 50));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 360, 10));

        lblErr1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblErr1.setForeground(new java.awt.Color(255, 0, 0));
        lblErr1.setText("* Veuillez renseigner ce champ");
        lblErr1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(lblErr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        lblErr1.setVisible(false);

        lblErr2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblErr2.setForeground(new java.awt.Color(255, 0, 0));
        lblErr2.setText("* Veuillez renseigner ce champ");
        lblErr2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(lblErr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        lblErr2.setVisible(false);

        lblErr3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblErr3.setForeground(new java.awt.Color(255, 0, 0));
        lblErr3.setText("* Veuillez renseigner ce champ");
        lblErr3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(lblErr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));
        lblErr3.setVisible(false);

        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameKeyReleased(evt);
            }
        });
        jPanel2.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 360, 40));

        txtPasswordConfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordConfirmKeyReleased(evt);
            }
        });
        jPanel2.add(txtPasswordConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 360, 40));

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 360, 40));

        btnNewAccount.setBackground(new java.awt.Color(51, 153, 255));
        btnNewAccount.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnNewAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qcm/img/add-user.png"))); // NOI18N
        btnNewAccount.setText("Créer mon compte");
        btnNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccountActionPerformed(evt);
            }
        });
        jPanel2.add(btnNewAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 190, 40));

        btnLogin.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qcm/img/login (2).png"))); // NOI18N
        btnLogin.setText("  Se connecter");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 160, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 400, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAccountActionPerformed

        String username = txtUserName.getText().toLowerCase().trim();
        String password = txtPassword.getText();
        String passwordConfirm = txtPasswordConfirm.getText();
        String md5pass = appUtils.md5Hash(password);
        boolean formChecked = false;
       

        //verification de champ username
        if (username.equals("")) {
            formChecked = false;
            fieldError1 = "* ce champ ne peut etre vide";
            txtUserName.requestFocus();

        } else if (username.length() < 4) {
            formChecked = false;
            txtUserName.requestFocus();
            fieldError1 = ("* au minimaum 4 caractères");
        }

        if (fieldError1 != null) {
            lblErr1.setText(fieldError1);
            lblErr1.setVisible(true);
            txtUserName.requestFocus();
        }

        //verification de champ password  
        if (password.equals("") || passwordConfirm.equals("")) {
            formChecked = false;
            fieldError3 = "* ce champ ne peut etre vide";
            fieldError2 = "* ce champ ne peut etre vide";

        } else if ((password.length() < 4) || (passwordConfirm.length() < 4)) {
            formChecked = false;
            fieldError2 = ("* au minimaum 4 caractères");
            fieldError3 = ("* au minimaum 4 caractères");
        }

        if (fieldError2 != null || fieldError3 != null ) {
            lblErr2.setText(fieldError2);
            lblErr3.setText(fieldError3);
            lblErr2.setVisible(true);
            lblErr3.setVisible(true);
            txtPassword.requestFocus();
        }

    
        if (!(password.equals(passwordConfirm))) {
            formChecked = false;
            fieldError2 = "Les deux mot de passe ne sont pas identiques";
            fieldError3 = "Les deux mot de passe ne sont pas identiques";
            txtPassword.requestFocus();
        } else {
            lblErr2.setVisible(false);
            lblErr3.setVisible(false);
            fieldError2 = null;
            fieldError3 = null;
        } 
      

        formChecked = (fieldError2 == null && fieldError1 == null);

        // si tout est bon nzido l user hedha fel base 
        if (formChecked == true && (password.equals(passwordConfirm)) && password.length()>= 4 && passwordConfirm.length()>= 4  && username.length()>= 4 ) {
            System.out.println("--------------------------On est prét ");
                String hash = appUtils.md5Hash(password);
                Person utilisateur = new Person(); 
                  utilisateur.setUsername(username);
                  utilisateur.setUserpass(hash);
                  utilisateur.setScore(0);
                  appUtils.registerUser(utilisateur);
                  appUtils.setActifUser(utilisateur);
                  javax.swing.JOptionPane.showMessageDialog(null, "L'utilisateur est inscrit avec succés", appUtils.nomProjet, INFORMATION_MESSAGE);
                  this.setVisible(false);
                  new qcmForm().setVisible(true);
        }
    


    }//GEN-LAST:event_btnNewAccountActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
                  this.setVisible(false);
                  new mainForm().setVisible(true);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased
                lblErr1.setVisible(false);
                fieldError1 = null;
    }//GEN-LAST:event_txtUserNameKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
            lblErr2.setVisible(false);
            fieldError2 = null;
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtPasswordConfirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordConfirmKeyReleased
            lblErr3.setVisible(false);
            fieldError3 = null;
    }//GEN-LAST:event_txtPasswordConfirmKeyReleased

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newAccoutnForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newAccoutnForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newAccoutnForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newAccoutnForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newAccoutnForm().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnNewAccount;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblErr1;
    private javax.swing.JLabel lblErr2;
    private javax.swing.JLabel lblErr3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordConfirm;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
